// PlantHub — Constants & Data

export const PRODUCTS = [
  {
    id: 1,
    name: "Dwarf Fiddle Leaf Fig",
    price: 1699,
    description: "A beautiful dwarf fiddle leaf fig that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=1",
    stock: 21,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 2,
    name: "Hybrid Mint",
    price: 119,
    description: "A beautiful hybrid mint that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=2",
    stock: 26,
    category: "Herb",
    careLevel: "Beginner",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 3,
    name: "Fragrant Mango Tree",
    price: 1679,
    description: "A beautiful fragrant mango tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=3",
    stock: 8,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 4,
    name: "Fragrant Bird of Paradise",
    price: 3859,
    description: "A beautiful fragrant bird of paradise that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=4",
    stock: 48,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Direct"
  },
  {
    id: 5,
    name: "Tropical String of Pearls",
    price: 259,
    description: "A beautiful tropical string of pearls that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=5",
    stock: 28,
    category: "Succulent",
    careLevel: "Moderate",
    lightReq: "Bright Direct"
  },
  {
    id: 6,
    name: "Desert Rubber Plant",
    price: 499,
    description: "A beautiful desert rubber plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=6",
    stock: 17,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 7,
    name: "Rosemary",
    price: 179,
    description: "A beautiful rosemary that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=7",
    stock: 32,
    category: "Herb",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 8,
    name: "Money Tree",
    price: 1019,
    description: "A beautiful money tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=8",
    stock: 23,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 9,
    name: "Areca Palm",
    price: 1779,
    description: "A beautiful areca palm that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=9",
    stock: 43,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 10,
    name: "Variegated Fiddle Leaf Fig",
    price: 2449,
    description: "A beautiful variegated fiddle leaf fig that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=10",
    stock: 48,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 11,
    name: "Royal Bird of Paradise",
    price: 1679,
    description: "A beautiful royal bird of paradise that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=11",
    stock: 25,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Direct"
  },
  {
    id: 12,
    name: "Desert Tulsi",
    price: 209,
    description: "A beautiful desert tulsi that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=12",
    stock: 38,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Direct",
    isNew: true
  },
  {
    id: 13,
    name: "Giant Bonsai Tree",
    price: 6629,
    description: "A beautiful giant bonsai tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=13",
    stock: 4,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 14,
    name: "Boston Fern",
    price: 349,
    description: "A beautiful boston fern that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=14",
    stock: 43,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 15,
    name: "Philodendron",
    price: 4129,
    description: "A beautiful philodendron that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/pottedplant?lock=15",
    stock: 49,
    category: "Rare",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 16,
    name: "Golden Peace Lily",
    price: 569,
    description: "A beautiful golden peace lily that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=16",
    stock: 41,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Low to Bright",
    isNew: true
  },
  {
    id: 17,
    name: "Sweet Money Tree",
    price: 1029,
    description: "A beautiful sweet money tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=17",
    stock: 21,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 18,
    name: "Variegated Areca Palm",
    price: 679,
    description: "A beautiful variegated areca palm that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=18",
    stock: 14,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect",
    isNew: true
  },
  {
    id: 19,
    name: "Premium ZZ Plant",
    price: 309,
    description: "A beautiful premium zz plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=19",
    stock: 40,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright"
  },
  {
    id: 20,
    name: "Desert Lemon Tree",
    price: 519,
    description: "A beautiful desert lemon tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=20",
    stock: 7,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 21,
    name: "Giant Coriander",
    price: 59,
    description: "A beautiful giant coriander that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=21",
    stock: 26,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Indirect",
    isNew: true
  },
  {
    id: 22,
    name: "Variegated Lemon Tree",
    price: 729,
    description: "A beautiful variegated lemon tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=22",
    stock: 37,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 23,
    name: "Giant Areca Palm",
    price: 599,
    description: "A beautiful giant areca palm that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=23",
    stock: 42,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 24,
    name: "Golden Areca Palm",
    price: 769,
    description: "A beautiful golden areca palm that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=24",
    stock: 41,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 25,
    name: "Fragrant Fiddle Leaf Fig",
    price: 819,
    description: "A beautiful fragrant fiddle leaf fig that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=25",
    stock: 15,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 26,
    name: "Areca Palm",
    price: 1769,
    description: "A beautiful areca palm that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=26",
    stock: 8,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 27,
    name: "Desert Mango Tree",
    price: 1289,
    description: "A beautiful desert mango tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=27",
    stock: 34,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 28,
    name: "Premium Bonsai Tree",
    price: 4519,
    description: "A beautiful premium bonsai tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=28",
    stock: 15,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 29,
    name: "Variegated Jasmine",
    price: 629,
    description: "A beautiful variegated jasmine that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=29",
    stock: 31,
    category: "Outdoor",
    careLevel: "Moderate",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 30,
    name: "Spider Plant",
    price: 159,
    description: "A beautiful spider plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=30",
    stock: 37,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright"
  },
  {
    id: 31,
    name: "Money Tree",
    price: 1159,
    description: "A beautiful money tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=31",
    stock: 23,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 32,
    name: "Royal Rosemary",
    price: 339,
    description: "A beautiful royal rosemary that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=32",
    stock: 32,
    category: "Herb",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 33,
    name: "Dwarf Jasmine",
    price: 259,
    description: "A beautiful dwarf jasmine that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=33",
    stock: 49,
    category: "Outdoor",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 34,
    name: "Monstera",
    price: 2489,
    description: "A beautiful monstera that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=34",
    stock: 46,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 35,
    name: "Wild Bird of Paradise",
    price: 1319,
    description: "A beautiful wild bird of paradise that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=35",
    stock: 49,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Direct"
  },
  {
    id: 36,
    name: "Jade Plant",
    price: 279,
    description: "A beautiful jade plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=36",
    stock: 40,
    category: "Succulent",
    careLevel: "Easy",
    lightReq: "Bright Direct"
  },
  {
    id: 37,
    name: "Premium Fiddle Leaf Fig",
    price: 1459,
    description: "A beautiful premium fiddle leaf fig that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=37",
    stock: 32,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 38,
    name: "Desert Litchi Tree",
    price: 939,
    description: "A beautiful desert litchi tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=38",
    stock: 32,
    category: "Fruit",
    careLevel: "Advanced",
    lightReq: "Full Sun"
  },
  {
    id: 39,
    name: "Cactus",
    price: 289,
    description: "A beautiful cactus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=39",
    stock: 4,
    category: "Succulent",
    careLevel: "Beginner",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 40,
    name: "Giant Peace Lily",
    price: 399,
    description: "A beautiful giant peace lily that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=40",
    stock: 11,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Low to Bright"
  },
  {
    id: 41,
    name: "Sweet Boston Fern",
    price: 239,
    description: "A beautiful sweet boston fern that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=41",
    stock: 35,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect",
    isNew: true
  },
  {
    id: 42,
    name: "Hibiscus",
    price: 539,
    description: "A beautiful hibiscus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=42",
    stock: 21,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 43,
    name: "Bougainvillea",
    price: 789,
    description: "A beautiful bougainvillea that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=43",
    stock: 18,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 44,
    name: "Golden ZZ Plant",
    price: 479,
    description: "A beautiful golden zz plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=44",
    stock: 30,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright"
  },
  {
    id: 45,
    name: "Sweet Lemon Tree",
    price: 459,
    description: "A beautiful sweet lemon tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=45",
    stock: 9,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 46,
    name: "Sweet Coriander",
    price: 99,
    description: "A beautiful sweet coriander that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=46",
    stock: 35,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 47,
    name: "Coriander",
    price: 89,
    description: "A beautiful coriander that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=47",
    stock: 49,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 48,
    name: "Calathea",
    price: 619,
    description: "A beautiful calathea that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=48",
    stock: 27,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect",
    isNew: true
  },
  {
    id: 49,
    name: "Hybrid Spider Plant",
    price: 159,
    description: "A beautiful hybrid spider plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=49",
    stock: 2,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright",
    isNew: true
  },
  {
    id: 50,
    name: "Desert Coriander",
    price: 99,
    description: "A beautiful desert coriander that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=50",
    stock: 12,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 51,
    name: "Tropical ZZ Plant",
    price: 349,
    description: "A beautiful tropical zz plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=51",
    stock: 8,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright"
  },
  {
    id: 52,
    name: "Hybrid Bird of Paradise",
    price: 2419,
    description: "A beautiful hybrid bird of paradise that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=52",
    stock: 14,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Direct",
    isNew: true
  },
  {
    id: 53,
    name: "Rubber Plant",
    price: 309,
    description: "A beautiful rubber plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=53",
    stock: 36,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 54,
    name: "Golden Monstera",
    price: 2179,
    description: "A beautiful golden monstera that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=54",
    stock: 23,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 55,
    name: "Royal Litchi Tree",
    price: 939,
    description: "A beautiful royal litchi tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=55",
    stock: 32,
    category: "Fruit",
    careLevel: "Advanced",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 56,
    name: "Wild Fiddle Leaf Fig",
    price: 2819,
    description: "A beautiful wild fiddle leaf fig that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=56",
    stock: 4,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 57,
    name: "Desert Bonsai Tree",
    price: 6759,
    description: "A beautiful desert bonsai tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=57",
    stock: 23,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 58,
    name: "Desert String of Pearls",
    price: 579,
    description: "A beautiful desert string of pearls that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=58",
    stock: 4,
    category: "Succulent",
    careLevel: "Moderate",
    lightReq: "Bright Direct"
  },
  {
    id: 59,
    name: "Sweet Boston Fern",
    price: 339,
    description: "A beautiful sweet boston fern that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=59",
    stock: 44,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 60,
    name: "Giant Tulsi",
    price: 259,
    description: "A beautiful giant tulsi that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=60",
    stock: 37,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Direct"
  },
  {
    id: 61,
    name: "Fragrant Bougainvillea",
    price: 779,
    description: "A beautiful fragrant bougainvillea that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=61",
    stock: 19,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 62,
    name: "Dwarf Orchid",
    price: 1079,
    description: "A beautiful dwarf orchid that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=62",
    stock: 35,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 63,
    name: "Golden Litchi Tree",
    price: 1469,
    description: "A beautiful golden litchi tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=63",
    stock: 40,
    category: "Fruit",
    careLevel: "Advanced",
    lightReq: "Full Sun"
  },
  {
    id: 64,
    name: "Fragrant Fiddle Leaf Fig",
    price: 1429,
    description: "A beautiful fragrant fiddle leaf fig that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=64",
    stock: 2,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 65,
    name: "Wild Lemon Tree",
    price: 519,
    description: "A beautiful wild lemon tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=65",
    stock: 35,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 66,
    name: "Royal Monstera",
    price: 2479,
    description: "A beautiful royal monstera that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=66",
    stock: 20,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 67,
    name: "Desert String of Pearls",
    price: 269,
    description: "A beautiful desert string of pearls that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=67",
    stock: 24,
    category: "Succulent",
    careLevel: "Moderate",
    lightReq: "Bright Direct",
    isNew: true
  },
  {
    id: 68,
    name: "Hybrid Jade Plant",
    price: 699,
    description: "A beautiful hybrid jade plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=68",
    stock: 5,
    category: "Succulent",
    careLevel: "Easy",
    lightReq: "Bright Direct"
  },
  {
    id: 69,
    name: "Hibiscus",
    price: 209,
    description: "A beautiful hibiscus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=69",
    stock: 19,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 70,
    name: "Tulsi",
    price: 129,
    description: "A beautiful tulsi that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=70",
    stock: 1,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Direct"
  },
  {
    id: 71,
    name: "Desert Bougainvillea",
    price: 799,
    description: "A beautiful desert bougainvillea that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=71",
    stock: 12,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 72,
    name: "Boston Fern",
    price: 249,
    description: "A beautiful boston fern that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=72",
    stock: 22,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 73,
    name: "Miniature Rubber Plant",
    price: 779,
    description: "A beautiful miniature rubber plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=73",
    stock: 41,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 74,
    name: "Rare Tulsi",
    price: 239,
    description: "A beautiful rare tulsi that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=74",
    stock: 13,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Direct"
  },
  {
    id: 75,
    name: "Philodendron",
    price: 3719,
    description: "A beautiful philodendron that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/pottedplant?lock=75",
    stock: 13,
    category: "Rare",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 76,
    name: "Miniature Boston Fern",
    price: 509,
    description: "A beautiful miniature boston fern that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=76",
    stock: 2,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 77,
    name: "Sweet Bonsai Tree",
    price: 6489,
    description: "A beautiful sweet bonsai tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=77",
    stock: 16,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 78,
    name: "Desert Areca Palm",
    price: 1299,
    description: "A beautiful desert areca palm that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=78",
    stock: 23,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 79,
    name: "Rare Money Tree",
    price: 1139,
    description: "A beautiful rare money tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=79",
    stock: 30,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 80,
    name: "Royal Papaya",
    price: 299,
    description: "A beautiful royal papaya that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=80",
    stock: 46,
    category: "Fruit",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 81,
    name: "Dwarf Rosemary",
    price: 299,
    description: "A beautiful dwarf rosemary that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=81",
    stock: 30,
    category: "Herb",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 82,
    name: "Tropical Snake Plant",
    price: 529,
    description: "A beautiful tropical snake plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=82",
    stock: 3,
    category: "Succulent",
    careLevel: "Beginner",
    lightReq: "Low to Bright",
    isNew: true
  },
  {
    id: 83,
    name: "Bird of Paradise",
    price: 2669,
    description: "A beautiful bird of paradise that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=83",
    stock: 28,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Direct"
  },
  {
    id: 84,
    name: "Mango Tree",
    price: 949,
    description: "A beautiful mango tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=84",
    stock: 4,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 85,
    name: "Premium Money Tree",
    price: 519,
    description: "A beautiful premium money tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=85",
    stock: 33,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 86,
    name: "Fiddle Leaf Fig",
    price: 1349,
    description: "A beautiful fiddle leaf fig that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=86",
    stock: 10,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 87,
    name: "Tropical Jasmine",
    price: 489,
    description: "A beautiful tropical jasmine that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=87",
    stock: 26,
    category: "Outdoor",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 88,
    name: "Miniature Bougainvillea",
    price: 709,
    description: "A beautiful miniature bougainvillea that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=88",
    stock: 2,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 89,
    name: "Royal Lemon Tree",
    price: 689,
    description: "A beautiful royal lemon tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=89",
    stock: 11,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 90,
    name: "Giant Monstera",
    price: 889,
    description: "A beautiful giant monstera that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=90",
    stock: 21,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 91,
    name: "Variegated Monstera",
    price: 509,
    description: "A beautiful variegated monstera that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=91",
    stock: 8,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 92,
    name: "Fragrant Philodendron",
    price: 799,
    description: "A beautiful fragrant philodendron that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/pottedplant?lock=92",
    stock: 9,
    category: "Rare",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 93,
    name: "Mango Tree",
    price: 1779,
    description: "A beautiful mango tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=93",
    stock: 4,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 94,
    name: "Variegated Coriander",
    price: 59,
    description: "A beautiful variegated coriander that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=94",
    stock: 29,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 95,
    name: "Jasmine",
    price: 659,
    description: "A beautiful jasmine that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=95",
    stock: 13,
    category: "Outdoor",
    careLevel: "Moderate",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 96,
    name: "Golden Bird of Paradise",
    price: 3799,
    description: "A beautiful golden bird of paradise that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=96",
    stock: 31,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Direct"
  },
  {
    id: 97,
    name: "String of Pearls",
    price: 419,
    description: "A beautiful string of pearls that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=97",
    stock: 49,
    category: "Succulent",
    careLevel: "Moderate",
    lightReq: "Bright Direct"
  },
  {
    id: 98,
    name: "Royal Pothos",
    price: 349,
    description: "A beautiful royal pothos that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=98",
    stock: 39,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright"
  },
  {
    id: 99,
    name: "Fragrant Tulsi",
    price: 119,
    description: "A beautiful fragrant tulsi that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=99",
    stock: 17,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Direct"
  },
  {
    id: 100,
    name: "Bonsai Tree",
    price: 5529,
    description: "A beautiful bonsai tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=100",
    stock: 20,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 101,
    name: "Bird of Paradise",
    price: 1129,
    description: "A beautiful bird of paradise that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=101",
    stock: 11,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Direct"
  },
  {
    id: 102,
    name: "Sweet Litchi Tree",
    price: 989,
    description: "A beautiful sweet litchi tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=102",
    stock: 4,
    category: "Fruit",
    careLevel: "Advanced",
    lightReq: "Full Sun"
  },
  {
    id: 103,
    name: "Sweet Bougainvillea",
    price: 699,
    description: "A beautiful sweet bougainvillea that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=103",
    stock: 44,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 104,
    name: "Royal Bougainvillea",
    price: 839,
    description: "A beautiful royal bougainvillea that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=104",
    stock: 24,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 105,
    name: "Rare Calathea",
    price: 829,
    description: "A beautiful rare calathea that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=105",
    stock: 45,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 106,
    name: "Wild Rosemary",
    price: 209,
    description: "A beautiful wild rosemary that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=106",
    stock: 46,
    category: "Herb",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 107,
    name: "Desert Monstera",
    price: 1319,
    description: "A beautiful desert monstera that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=107",
    stock: 2,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 108,
    name: "Jasmine",
    price: 439,
    description: "A beautiful jasmine that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=108",
    stock: 39,
    category: "Outdoor",
    careLevel: "Moderate",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 109,
    name: "Royal Boston Fern",
    price: 269,
    description: "A beautiful royal boston fern that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=109",
    stock: 20,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 110,
    name: "Golden Hibiscus",
    price: 529,
    description: "A beautiful golden hibiscus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=110",
    stock: 21,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 111,
    name: "Golden Orchid",
    price: 759,
    description: "A beautiful golden orchid that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=111",
    stock: 44,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 112,
    name: "Premium Rosemary",
    price: 319,
    description: "A beautiful premium rosemary that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=112",
    stock: 2,
    category: "Herb",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 113,
    name: "Giant Pothos",
    price: 229,
    description: "A beautiful giant pothos that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=113",
    stock: 12,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright"
  },
  {
    id: 114,
    name: "Variegated Bonsai Tree",
    price: 2439,
    description: "A beautiful variegated bonsai tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=114",
    stock: 21,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 115,
    name: "Orchid",
    price: 899,
    description: "A beautiful orchid that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=115",
    stock: 18,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 116,
    name: "Dwarf Hibiscus",
    price: 579,
    description: "A beautiful dwarf hibiscus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=116",
    stock: 20,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 117,
    name: "String of Pearls",
    price: 369,
    description: "A beautiful string of pearls that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=117",
    stock: 12,
    category: "Succulent",
    careLevel: "Moderate",
    lightReq: "Bright Direct"
  },
  {
    id: 118,
    name: "Hibiscus",
    price: 389,
    description: "A beautiful hibiscus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=118",
    stock: 46,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 119,
    name: "Rare Aloe Vera",
    price: 339,
    description: "A beautiful rare aloe vera that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=119",
    stock: 21,
    category: "Succulent",
    careLevel: "Easy",
    lightReq: "Bright Direct"
  },
  {
    id: 120,
    name: "Premium Orchid",
    price: 719,
    description: "A beautiful premium orchid that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=120",
    stock: 21,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 121,
    name: "Jade Plant",
    price: 829,
    description: "A beautiful jade plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=121",
    stock: 30,
    category: "Succulent",
    careLevel: "Easy",
    lightReq: "Bright Direct"
  },
  {
    id: 122,
    name: "Jade Plant",
    price: 659,
    description: "A beautiful jade plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=122",
    stock: 38,
    category: "Succulent",
    careLevel: "Easy",
    lightReq: "Bright Direct"
  },
  {
    id: 123,
    name: "Fragrant Monstera",
    price: 1669,
    description: "A beautiful fragrant monstera that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=123",
    stock: 47,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 124,
    name: "Premium String of Pearls",
    price: 579,
    description: "A beautiful premium string of pearls that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=124",
    stock: 1,
    category: "Succulent",
    careLevel: "Moderate",
    lightReq: "Bright Direct",
    isNew: true
  },
  {
    id: 125,
    name: "ZZ Plant",
    price: 329,
    description: "A beautiful zz plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=125",
    stock: 5,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright"
  },
  {
    id: 126,
    name: "Tropical Tulsi",
    price: 179,
    description: "A beautiful tropical tulsi that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=126",
    stock: 10,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Direct",
    isNew: true
  },
  {
    id: 127,
    name: "Premium String of Pearls",
    price: 329,
    description: "A beautiful premium string of pearls that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=127",
    stock: 9,
    category: "Succulent",
    careLevel: "Moderate",
    lightReq: "Bright Direct",
    isNew: true
  },
  {
    id: 128,
    name: "Hibiscus",
    price: 679,
    description: "A beautiful hibiscus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=128",
    stock: 34,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 129,
    name: "Dwarf Hibiscus",
    price: 529,
    description: "A beautiful dwarf hibiscus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=129",
    stock: 18,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 130,
    name: "Philodendron",
    price: 2709,
    description: "A beautiful philodendron that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/pottedplant?lock=130",
    stock: 6,
    category: "Rare",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 131,
    name: "Rare Bonsai Tree",
    price: 8459,
    description: "A beautiful rare bonsai tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=131",
    stock: 39,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 132,
    name: "Tropical Coriander",
    price: 89,
    description: "A beautiful tropical coriander that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=132",
    stock: 22,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 133,
    name: "Desert String of Pearls",
    price: 559,
    description: "A beautiful desert string of pearls that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=133",
    stock: 17,
    category: "Succulent",
    careLevel: "Moderate",
    lightReq: "Bright Direct"
  },
  {
    id: 134,
    name: "Dwarf Rosemary",
    price: 199,
    description: "A beautiful dwarf rosemary that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=134",
    stock: 25,
    category: "Herb",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 135,
    name: "Miniature Jasmine",
    price: 679,
    description: "A beautiful miniature jasmine that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=135",
    stock: 46,
    category: "Outdoor",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 136,
    name: "Wild Litchi Tree",
    price: 1119,
    description: "A beautiful wild litchi tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=136",
    stock: 11,
    category: "Fruit",
    careLevel: "Advanced",
    lightReq: "Full Sun"
  },
  {
    id: 137,
    name: "Hibiscus",
    price: 229,
    description: "A beautiful hibiscus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=137",
    stock: 40,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 138,
    name: "Wild Tulsi",
    price: 239,
    description: "A beautiful wild tulsi that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=138",
    stock: 13,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Direct"
  },
  {
    id: 139,
    name: "Wild Fiddle Leaf Fig",
    price: 1169,
    description: "A beautiful wild fiddle leaf fig that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=139",
    stock: 9,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 140,
    name: "Dwarf Rosemary",
    price: 369,
    description: "A beautiful dwarf rosemary that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=140",
    stock: 27,
    category: "Herb",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 141,
    name: "Silver Hibiscus",
    price: 599,
    description: "A beautiful silver hibiscus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=141",
    stock: 47,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 142,
    name: "Mango Tree",
    price: 1029,
    description: "A beautiful mango tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=142",
    stock: 21,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 143,
    name: "Philodendron",
    price: 1359,
    description: "A beautiful philodendron that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/pottedplant?lock=143",
    stock: 31,
    category: "Rare",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 144,
    name: "Mint",
    price: 89,
    description: "A beautiful mint that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=144",
    stock: 1,
    category: "Herb",
    careLevel: "Beginner",
    lightReq: "Full Sun"
  },
  {
    id: 145,
    name: "Silver Papaya",
    price: 449,
    description: "A beautiful silver papaya that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=145",
    stock: 29,
    category: "Fruit",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 146,
    name: "Hybrid Mango Tree",
    price: 1129,
    description: "A beautiful hybrid mango tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=146",
    stock: 38,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 147,
    name: "Spider Plant",
    price: 229,
    description: "A beautiful spider plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=147",
    stock: 42,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright"
  },
  {
    id: 148,
    name: "Bird of Paradise",
    price: 2909,
    description: "A beautiful bird of paradise that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=148",
    stock: 47,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Direct"
  },
  {
    id: 149,
    name: "Tropical Monstera",
    price: 589,
    description: "A beautiful tropical monstera that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=149",
    stock: 31,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 150,
    name: "Giant Calathea",
    price: 639,
    description: "A beautiful giant calathea that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=150",
    stock: 30,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect",
    isNew: true
  },
  {
    id: 151,
    name: "Cactus",
    price: 849,
    description: "A beautiful cactus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=151",
    stock: 40,
    category: "Succulent",
    careLevel: "Beginner",
    lightReq: "Full Sun"
  },
  {
    id: 152,
    name: "Desert Pothos",
    price: 289,
    description: "A beautiful desert pothos that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=152",
    stock: 50,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright"
  },
  {
    id: 153,
    name: "Rare Peace Lily",
    price: 669,
    description: "A beautiful rare peace lily that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=153",
    stock: 33,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Low to Bright",
    isNew: true
  },
  {
    id: 154,
    name: "Giant Lemon Tree",
    price: 489,
    description: "A beautiful giant lemon tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=154",
    stock: 39,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 155,
    name: "Royal Bougainvillea",
    price: 899,
    description: "A beautiful royal bougainvillea that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=155",
    stock: 49,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 156,
    name: "Wild Jasmine",
    price: 399,
    description: "A beautiful wild jasmine that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=156",
    stock: 17,
    category: "Outdoor",
    careLevel: "Moderate",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 157,
    name: "Royal Coriander",
    price: 69,
    description: "A beautiful royal coriander that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=157",
    stock: 10,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 158,
    name: "Miniature Fiddle Leaf Fig",
    price: 2209,
    description: "A beautiful miniature fiddle leaf fig that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=158",
    stock: 9,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 159,
    name: "Royal Bird of Paradise",
    price: 2929,
    description: "A beautiful royal bird of paradise that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=159",
    stock: 18,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Direct"
  },
  {
    id: 160,
    name: "Fiddle Leaf Fig",
    price: 719,
    description: "A beautiful fiddle leaf fig that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=160",
    stock: 39,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 161,
    name: "Tropical Spider Plant",
    price: 249,
    description: "A beautiful tropical spider plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=161",
    stock: 29,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright"
  },
  {
    id: 162,
    name: "Variegated Lemon Tree",
    price: 779,
    description: "A beautiful variegated lemon tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=162",
    stock: 4,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 163,
    name: "Royal String of Pearls",
    price: 269,
    description: "A beautiful royal string of pearls that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=163",
    stock: 15,
    category: "Succulent",
    careLevel: "Moderate",
    lightReq: "Bright Direct",
    isNew: true
  },
  {
    id: 164,
    name: "Philodendron",
    price: 2909,
    description: "A beautiful philodendron that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/pottedplant?lock=164",
    stock: 16,
    category: "Rare",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 165,
    name: "Papaya",
    price: 309,
    description: "A beautiful papaya that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=165",
    stock: 12,
    category: "Fruit",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 166,
    name: "Hybrid Philodendron",
    price: 2599,
    description: "A beautiful hybrid philodendron that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/pottedplant?lock=166",
    stock: 28,
    category: "Rare",
    careLevel: "Advanced",
    lightReq: "Bright Indirect",
    isNew: true
  },
  {
    id: 167,
    name: "Miniature Hibiscus",
    price: 239,
    description: "A beautiful miniature hibiscus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=167",
    stock: 5,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 168,
    name: "Hybrid ZZ Plant",
    price: 809,
    description: "A beautiful hybrid zz plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=168",
    stock: 7,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright",
    isNew: true
  },
  {
    id: 169,
    name: "Dwarf Litchi Tree",
    price: 1129,
    description: "A beautiful dwarf litchi tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=169",
    stock: 39,
    category: "Fruit",
    careLevel: "Advanced",
    lightReq: "Full Sun"
  },
  {
    id: 170,
    name: "Rosemary",
    price: 169,
    description: "A beautiful rosemary that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=170",
    stock: 26,
    category: "Herb",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 171,
    name: "Variegated Tulsi",
    price: 239,
    description: "A beautiful variegated tulsi that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=171",
    stock: 47,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Direct"
  },
  {
    id: 172,
    name: "Desert Monstera",
    price: 799,
    description: "A beautiful desert monstera that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=172",
    stock: 33,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 173,
    name: "Sweet Jasmine",
    price: 319,
    description: "A beautiful sweet jasmine that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=173",
    stock: 25,
    category: "Outdoor",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 174,
    name: "Variegated Litchi Tree",
    price: 829,
    description: "A beautiful variegated litchi tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=174",
    stock: 48,
    category: "Fruit",
    careLevel: "Advanced",
    lightReq: "Full Sun"
  },
  {
    id: 175,
    name: "Rare Peace Lily",
    price: 259,
    description: "A beautiful rare peace lily that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=175",
    stock: 16,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Low to Bright"
  },
  {
    id: 176,
    name: "Tropical Jasmine",
    price: 219,
    description: "A beautiful tropical jasmine that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=176",
    stock: 22,
    category: "Outdoor",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 177,
    name: "Mango Tree",
    price: 1179,
    description: "A beautiful mango tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=177",
    stock: 44,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 178,
    name: "Wild Tulsi",
    price: 259,
    description: "A beautiful wild tulsi that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=178",
    stock: 10,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Direct",
    isNew: true
  },
  {
    id: 179,
    name: "Hybrid Bonsai Tree",
    price: 7649,
    description: "A beautiful hybrid bonsai tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=179",
    stock: 11,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 180,
    name: "Variegated Fiddle Leaf Fig",
    price: 1919,
    description: "A beautiful variegated fiddle leaf fig that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=180",
    stock: 8,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 181,
    name: "Rubber Plant",
    price: 359,
    description: "A beautiful rubber plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=181",
    stock: 1,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 182,
    name: "Cactus",
    price: 839,
    description: "A beautiful cactus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=182",
    stock: 17,
    category: "Succulent",
    careLevel: "Beginner",
    lightReq: "Full Sun"
  },
  {
    id: 183,
    name: "Silver Aloe Vera",
    price: 239,
    description: "A beautiful silver aloe vera that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=183",
    stock: 46,
    category: "Succulent",
    careLevel: "Easy",
    lightReq: "Bright Direct",
    isNew: true
  },
  {
    id: 184,
    name: "Papaya",
    price: 429,
    description: "A beautiful papaya that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=184",
    stock: 30,
    category: "Fruit",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 185,
    name: "Boston Fern",
    price: 439,
    description: "A beautiful boston fern that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=185",
    stock: 9,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 186,
    name: "Rosemary",
    price: 389,
    description: "A beautiful rosemary that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=186",
    stock: 1,
    category: "Herb",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 187,
    name: "Premium Monstera",
    price: 2479,
    description: "A beautiful premium monstera that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=187",
    stock: 28,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect",
    isNew: true
  },
  {
    id: 188,
    name: "Tropical Boston Fern",
    price: 239,
    description: "A beautiful tropical boston fern that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=188",
    stock: 20,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect",
    isNew: true
  },
  {
    id: 189,
    name: "Dwarf Monstera",
    price: 2289,
    description: "A beautiful dwarf monstera that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=189",
    stock: 12,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 190,
    name: "Silver Mint",
    price: 79,
    description: "A beautiful silver mint that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=190",
    stock: 22,
    category: "Herb",
    careLevel: "Beginner",
    lightReq: "Full Sun"
  },
  {
    id: 191,
    name: "Desert Papaya",
    price: 219,
    description: "A beautiful desert papaya that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=191",
    stock: 13,
    category: "Fruit",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 192,
    name: "Golden Spider Plant",
    price: 179,
    description: "A beautiful golden spider plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=192",
    stock: 1,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright",
    isNew: true
  },
  {
    id: 193,
    name: "Royal Mango Tree",
    price: 999,
    description: "A beautiful royal mango tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=193",
    stock: 9,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 194,
    name: "Bonsai Tree",
    price: 7159,
    description: "A beautiful bonsai tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=194",
    stock: 29,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 195,
    name: "Tropical Mango Tree",
    price: 1329,
    description: "A beautiful tropical mango tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=195",
    stock: 45,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 196,
    name: "Golden Peace Lily",
    price: 579,
    description: "A beautiful golden peace lily that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=196",
    stock: 19,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Low to Bright"
  },
  {
    id: 197,
    name: "Wild Bird of Paradise",
    price: 3049,
    description: "A beautiful wild bird of paradise that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=197",
    stock: 50,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Direct"
  },
  {
    id: 198,
    name: "Dwarf Hibiscus",
    price: 299,
    description: "A beautiful dwarf hibiscus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=198",
    stock: 29,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 199,
    name: "Miniature Bird of Paradise",
    price: 969,
    description: "A beautiful miniature bird of paradise that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=199",
    stock: 46,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Direct"
  },
  {
    id: 200,
    name: "Miniature Cactus",
    price: 829,
    description: "A beautiful miniature cactus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=200",
    stock: 13,
    category: "Succulent",
    careLevel: "Beginner",
    lightReq: "Full Sun"
  },
  {
    id: 201,
    name: "Wild Bougainvillea",
    price: 569,
    description: "A beautiful wild bougainvillea that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=201",
    stock: 26,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 202,
    name: "Wild Rubber Plant",
    price: 769,
    description: "A beautiful wild rubber plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=202",
    stock: 34,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 203,
    name: "Rare Bougainvillea",
    price: 949,
    description: "A beautiful rare bougainvillea that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=203",
    stock: 10,
    category: "Outdoor",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 204,
    name: "Variegated Philodendron",
    price: 2409,
    description: "A beautiful variegated philodendron that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/pottedplant?lock=204",
    stock: 25,
    category: "Rare",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 205,
    name: "Hybrid Peace Lily",
    price: 449,
    description: "A beautiful hybrid peace lily that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=205",
    stock: 24,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Low to Bright"
  },
  {
    id: 206,
    name: "Wild Pothos",
    price: 209,
    description: "A beautiful wild pothos that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=206",
    stock: 11,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright"
  },
  {
    id: 207,
    name: "Giant Boston Fern",
    price: 399,
    description: "A beautiful giant boston fern that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=207",
    stock: 8,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 208,
    name: "Dwarf Snake Plant",
    price: 889,
    description: "A beautiful dwarf snake plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=208",
    stock: 28,
    category: "Succulent",
    careLevel: "Beginner",
    lightReq: "Low to Bright",
    isNew: true
  },
  {
    id: 209,
    name: "Monstera",
    price: 1979,
    description: "A beautiful monstera that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=209",
    stock: 41,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 210,
    name: "Philodendron",
    price: 3539,
    description: "A beautiful philodendron that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/pottedplant?lock=210",
    stock: 33,
    category: "Rare",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 211,
    name: "Dwarf Litchi Tree",
    price: 769,
    description: "A beautiful dwarf litchi tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=211",
    stock: 3,
    category: "Fruit",
    careLevel: "Advanced",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 212,
    name: "Premium Tulsi",
    price: 169,
    description: "A beautiful premium tulsi that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=212",
    stock: 49,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Direct"
  },
  {
    id: 213,
    name: "Wild Rosemary",
    price: 199,
    description: "A beautiful wild rosemary that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=213",
    stock: 17,
    category: "Herb",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 214,
    name: "Papaya",
    price: 279,
    description: "A beautiful papaya that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=214",
    stock: 3,
    category: "Fruit",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 215,
    name: "Premium Litchi Tree",
    price: 1469,
    description: "A beautiful premium litchi tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=215",
    stock: 12,
    category: "Fruit",
    careLevel: "Advanced",
    lightReq: "Full Sun"
  },
  {
    id: 216,
    name: "Jade Plant",
    price: 199,
    description: "A beautiful jade plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=216",
    stock: 26,
    category: "Succulent",
    careLevel: "Easy",
    lightReq: "Bright Direct",
    isNew: true
  },
  {
    id: 217,
    name: "Jasmine",
    price: 259,
    description: "A beautiful jasmine that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/outdoorplant,pot?lock=217",
    stock: 29,
    category: "Outdoor",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 218,
    name: "Hybrid Calathea",
    price: 609,
    description: "A beautiful hybrid calathea that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=218",
    stock: 44,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 219,
    name: "Bonsai Tree",
    price: 3779,
    description: "A beautiful bonsai tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=219",
    stock: 3,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 220,
    name: "Tropical Mango Tree",
    price: 1049,
    description: "A beautiful tropical mango tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=220",
    stock: 50,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 221,
    name: "Royal Fiddle Leaf Fig",
    price: 2799,
    description: "A beautiful royal fiddle leaf fig that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=221",
    stock: 33,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 222,
    name: "Monstera",
    price: 1689,
    description: "A beautiful monstera that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=222",
    stock: 10,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 223,
    name: "Miniature Bird of Paradise",
    price: 1899,
    description: "A beautiful miniature bird of paradise that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=223",
    stock: 23,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Direct",
    isNew: true
  },
  {
    id: 224,
    name: "Spider Plant",
    price: 389,
    description: "A beautiful spider plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=224",
    stock: 42,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright"
  },
  {
    id: 225,
    name: "Money Tree",
    price: 1059,
    description: "A beautiful money tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=225",
    stock: 4,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 226,
    name: "Royal Calathea",
    price: 859,
    description: "A beautiful royal calathea that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=226",
    stock: 37,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 227,
    name: "Miniature Peace Lily",
    price: 249,
    description: "A beautiful miniature peace lily that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=227",
    stock: 3,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Low to Bright"
  },
  {
    id: 228,
    name: "Sweet Snake Plant",
    price: 899,
    description: "A beautiful sweet snake plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=228",
    stock: 37,
    category: "Succulent",
    careLevel: "Beginner",
    lightReq: "Low to Bright"
  },
  {
    id: 229,
    name: "Litchi Tree",
    price: 1409,
    description: "A beautiful litchi tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=229",
    stock: 50,
    category: "Fruit",
    careLevel: "Advanced",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 230,
    name: "Rare Philodendron",
    price: 4169,
    description: "A beautiful rare philodendron that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/pottedplant?lock=230",
    stock: 49,
    category: "Rare",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 231,
    name: "Rare Coriander",
    price: 59,
    description: "A beautiful rare coriander that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=231",
    stock: 2,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 232,
    name: "Golden Mint",
    price: 99,
    description: "A beautiful golden mint that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=232",
    stock: 36,
    category: "Herb",
    careLevel: "Beginner",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 233,
    name: "Dwarf Boston Fern",
    price: 369,
    description: "A beautiful dwarf boston fern that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=233",
    stock: 7,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect"
  },
  {
    id: 234,
    name: "Wild Lemon Tree",
    price: 319,
    description: "A beautiful wild lemon tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=234",
    stock: 23,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 235,
    name: "Miniature Orchid",
    price: 789,
    description: "A beautiful miniature orchid that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=235",
    stock: 35,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 236,
    name: "Golden Rubber Plant",
    price: 849,
    description: "A beautiful golden rubber plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=236",
    stock: 49,
    category: "Indoor",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 237,
    name: "Boston Fern",
    price: 589,
    description: "A beautiful boston fern that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=237",
    stock: 38,
    category: "Indoor",
    careLevel: "Moderate",
    lightReq: "Bright Indirect",
    isNew: true
  },
  {
    id: 238,
    name: "Golden Mint",
    price: 129,
    description: "A beautiful golden mint that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=238",
    stock: 36,
    category: "Herb",
    careLevel: "Beginner",
    lightReq: "Full Sun"
  },
  {
    id: 239,
    name: "Dwarf Papaya",
    price: 439,
    description: "A beautiful dwarf papaya that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=239",
    stock: 1,
    category: "Fruit",
    careLevel: "Easy",
    lightReq: "Full Sun"
  },
  {
    id: 240,
    name: "Cactus",
    price: 479,
    description: "A beautiful cactus that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/succulent,pot?lock=240",
    stock: 48,
    category: "Succulent",
    careLevel: "Beginner",
    lightReq: "Full Sun"
  },
  {
    id: 241,
    name: "Giant Bird of Paradise",
    price: 2729,
    description: "A beautiful giant bird of paradise that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=241",
    stock: 23,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Direct"
  },
  {
    id: 242,
    name: "Dwarf Tulsi",
    price: 189,
    description: "A beautiful dwarf tulsi that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=242",
    stock: 8,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Direct"
  },
  {
    id: 243,
    name: "Sweet Papaya",
    price: 389,
    description: "A beautiful sweet papaya that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=243",
    stock: 41,
    category: "Fruit",
    careLevel: "Easy",
    lightReq: "Full Sun",
    isNew: true
  },
  {
    id: 244,
    name: "Dwarf Coriander",
    price: 89,
    description: "A beautiful dwarf coriander that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=244",
    stock: 39,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Indirect"
  },
  {
    id: 245,
    name: "Royal Orchid",
    price: 539,
    description: "A beautiful royal orchid that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=245",
    stock: 43,
    category: "Indoor",
    careLevel: "Advanced",
    lightReq: "Bright Indirect"
  },
  {
    id: 246,
    name: "Mint",
    price: 89,
    description: "A beautiful mint that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=246",
    stock: 36,
    category: "Herb",
    careLevel: "Beginner",
    lightReq: "Full Sun"
  },
  {
    id: 247,
    name: "Hybrid Mint",
    price: 139,
    description: "A beautiful hybrid mint that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=247",
    stock: 13,
    category: "Herb",
    careLevel: "Beginner",
    lightReq: "Full Sun"
  },
  {
    id: 248,
    name: "Lemon Tree",
    price: 419,
    description: "A beautiful lemon tree that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/fruittree,pot?lock=248",
    stock: 13,
    category: "Fruit",
    careLevel: "Moderate",
    lightReq: "Full Sun"
  },
  {
    id: 249,
    name: "Sweet ZZ Plant",
    price: 429,
    description: "A beautiful sweet zz plant that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/indoorplant,pot?lock=249",
    stock: 35,
    category: "Indoor",
    careLevel: "Beginner",
    lightReq: "Low to Bright"
  },
  {
    id: 250,
    name: "Royal Tulsi",
    price: 249,
    description: "A beautiful royal tulsi that brings life to your space. Perfect for any plant lover.",
    image: "https://loremflickr.com/800/800/herb,pot?lock=250",
    stock: 32,
    category: "Herb",
    careLevel: "Easy",
    lightReq: "Bright Direct"
  }
];

export const CATEGORIES = ['All', 'Indoor', 'Succulent', 'Herb', 'Fruit'];

export const CHART_DATA = [
  { month: 'Jan', sales: 4000, orders: 240 },
  { month: 'Feb', sales: 3000, orders: 221 },
  { month: 'Mar', sales: 5200, orders: 329 },
  { month: 'Apr', sales: 2780, orders: 200 },
  { month: 'May', sales: 4890, orders: 329 },
  { month: 'Jun', sales: 6390, orders: 400 },
  { month: 'Jul', sales: 5490, orders: 350 },
  { month: 'Aug', sales: 7200, orders: 420 },
];

export const PIE_DATA = [
  { name: 'Indoor Plants', value: 45 },
  { name: 'Succulents', value: 30 },
  { name: 'Herbs', value: 25 },
];

export const PIE_COLORS = ['#10b981', '#06b6d4', '#f59e0b'];

export const DEMO_ORDERS = [
  {
    id: 'ORD001',
    items: [{ id: 8, name: 'Monstera Deliciosa', qty: 1, price: 599, image: '🍃' }],
    total: 599,
    status: 'delivered',
    date: '2024-08-20',
    trackingNumber: 'TRK-PH-001',
  },
  {
    id: 'ORD002',
    items: [{ id: 9, name: 'Snake Plant', qty: 2, price: 299, image: '🎋' }],
    total: 598,
    status: 'shipped',
    date: '2024-09-01',
    trackingNumber: 'TRK-PH-002',
  },
  {
    id: 'ORD003',
    items: [
      { id: 1, name: 'Alphonso Mango Tree', qty: 1, price: 899, image: '🍂' },
      { id: 10, name: 'Aloe Vera', qty: 1, price: 199, image: '🌿' },
    ],
    total: 1098,
    status: 'pending',
    date: '2024-09-10',
    trackingNumber: 'TRK-PH-003',
  },
];

export const TESTIMONIALS = [
  {
    quote: "PlantHub transformed my apartment into a green paradise. The plants arrived in perfect condition and the care guides were incredibly helpful!",
    name: 'Sarah Johnson',
    role: 'Happy Customer',
    avatar: 'SJ',
  },
  {
    quote: "Best online plant shop I've ever used. Fast delivery, healthy plants, and amazing customer service. Highly recommended!",
    name: 'Michael Chen',
    role: 'Plant Enthusiast',
    avatar: 'MC',
  },
  {
    quote: "I'm a beginner plant parent and PlantHub made it so easy to get started. The low-maintenance recommendations were spot on.",
    name: 'Emily Rodriguez',
    role: 'New Plant Mom',
    avatar: 'ER',
  },
];

export const FEATURES = [
  {
    icon: '🌿',
    title: 'Premium Quality',
    description: 'Every plant is hand-selected from trusted growers and inspected before shipping.',
  },
  {
    icon: '🚚',
    title: 'Fast Delivery',
    description: 'Ships within 48 hours with real-time tracking. Safely packaged for transit.',
  },
  {
    icon: '💬',
    title: 'Expert Support',
    description: 'Our plant care team is here to help with tips, troubleshooting, and recommendations.',
  },
  {
    icon: '🔄',
    title: '30-Day Guarantee',
    description: 'Not happy? Return within 30 days for a full refund. No questions asked.',
  },
  {
    icon: '📦',
    title: 'Eco Packaging',
    description: 'Sustainable, biodegradable packaging that protects your plants and the planet.',
  },
  {
    icon: '🏆',
    title: 'Loyalty Rewards',
    description: 'Earn points with every purchase. Redeem for discounts on future orders.',
  },
];

export const FEEDBACK_CATEGORIES = [
  'Product Quality',
  'Delivery Experience',
  'Customer Service',
  'Website Experience',
  'Packaging',
  'Other',
];
